### ISSUE TITLE
crasheson android with React Native 0.70.6

### ISSUE THREAD

**Issue by hugoh59** [IjzerenHein/react-native-shared-element#106]
Getting the following error message when trying to run on android after upgrading to rn 0.70.6

````
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-shared-element' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21
````

**Comment by IjzerenHein** [comment]
Is it a "crash", or the is "build failing"? Those are two quite distinct things in my experience.

The message you are getting seems more warning-ish to be honest. But still, I've updated the project so that it now used the Kotlin plugin 1.6 by default. You can always override/configure it in your app build.gradle or properties.

Released as:
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.8.6
