### ISSUE TITLE
Updates to contents of shared element are not rendered

### ISSUE THREAD

**Issue by forabi** [IjzerenHein/react-native-shared-element#11]
I have a single-screen shared element transition that toggles between two states of the navigation bar (expanded, collapsed). The expanded state has a switch control (to control locked vs unlocked states) that when toggled, should update the text in the collapsed state to match ("Unlocked", "Locked"). Even though the switch works, when going back to the collapsed state, the text still reflects the older state and never updates. Is there a way to force the shared element to re-render?

**Comment by IjzerenHein** [comment]
Does this refer to `react-navigation-shared-element`? Can you share an animated gif concerning the problem?

**Comment by forabi** [comment]
@IjzerenHein I'm using `react-native-navigation` (not `react-navigation`) but the parts that include the elements do not use any components from `react-native-navigation`. Here's a reproduction (you can see the updates contents overlapping the snapshot):

![Screen Recording 2019-12-12 at 5 19 56 PM copy 2019-12-12 17_25_15](https://user-images.githubusercontent.com/1012761/70725115-78ae8780-1d04-11ea-86c9-be7d0cf41177.gif)

**Comment by IjzerenHein** [comment]
Screenshot just before overlap:

![image](https://user-images.githubusercontent.com/6184593/71896276-a2b46780-3153-11ea-8b4d-a214b72c9b5c.png)

**Comment by IjzerenHein** [comment]
Hi! I guess that would be somewhat possible, but I also reckon it would cause "jumps" in the animation because the source image changes size. 

The thing I don't understand here is, how both the shared-element-transition and the target-element are visible. When the animation starts, it should have hidden the start- and end-elements. It almost looks like the code renders both the locked- and unlocked state Views, and you are selecting the wrong one. Could that be the case?
