### ISSUE TITLE
Support binding for expo

### ISSUE THREAD

**Issue by kelvin-dev** [IjzerenHein/react-native-shared-element#89]
Hi team,
Please help support the concept of SharedElementGroup from Expo eco apps that would give huge impact on Expo communities
Reference: 
[Expo SharedElementGroup concept](https://github.com/expo/ex-navigation/blob/master/src/shared-element/ExNavigationSharedElementGroup.js)
Cheers,

**Comment by p-syche** [comment]
Hi @kelvin-dev !

Thank you for your comment.
The enhancement you're asking for sounds very nice. Unfortunately the library author won't be able to add it in the near future. Maybe you can take a crack at it and open a PR? 

I'm closing this issue since it's not reporting any problem with the library.
